// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOhgv48R99hgrNGz9n4FBvO0-pYrk0Oms',
    appId: '1:960751971143:web:e9c9ca4a42f7e65171ba62',
    messagingSenderId: '960751971143',
    projectId: 'bk-compare-prices',
    authDomain: 'bk-compare-prices.firebaseapp.com',
    storageBucket: 'bk-compare-prices.appspot.com',
    measurementId: 'G-LQBPMGY688',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACQD5lG6AYGp0y0jvuxjMT1CKQ6jOfYCE',
    appId: '1:960751971143:android:93b69266a0492ff871ba62',
    messagingSenderId: '960751971143',
    projectId: 'bk-compare-prices',
    storageBucket: 'bk-compare-prices.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3ROhm8tdvuxpTiaFv61esNZX-Kdnnos4',
    appId: '1:960751971143:ios:87541d67d965267d71ba62',
    messagingSenderId: '960751971143',
    projectId: 'bk-compare-prices',
    storageBucket: 'bk-compare-prices.appspot.com',
    iosBundleId: 'com.example.comparePrices',
  );
}
